# secrets.toml — do NOT commit to public repos
OPENAI_API_KEY = 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
SERPAPI_API_KEY = 463955e71f9dbeed6e2114b5c3fae642e33ed4d6a8d6a3625f47a4633f86a757
